### PR TITLE
Api changes for work experience id

### PR DESCRIPTION
**Pull request by julman**
Adding support for work experience ID in place of "job title" in the salary section of resume.
Also adding work experience ID as a field in the work experience section of resume.

https://careerbuilder.mingle.thoughtworks.com/projects/job_discovery_ux__search___re/cards/768

### CODE REVIEW

**Comment by helious** [comment]
changelog entry por favour

**Comment by julman** [comment]
oo good one

**Comment by cblant20** [comment]
no description? Can you include the card, a brief description of what you're working on, and verification steps?

**Comment by julman** [comment]
updated the comment

**Comment by NicholasBusby** [comment]
@helious you beat me to it by 2 seconds

**Pull request merged**
